/**
 * PCB Creation catalog: batteries
 * Verified fields (LCSC number, manufacturer part number, datasheet and LCSC
 * links, package) come from the yaqwsx/jlcparts dataset. Pros, cons, use notes,
 * and typical current figures are curated. Entries marked verified:false have no
 * single confirmed LCSC part. Generated by scripts/build-catalog.py.
 */
export const batteries = [
  {
    "id": "cat_cr2032_coin_cell_3_volts",
    "category": "battery",
    "subtype": "Coin cell",
    "name": "CR2032 coin cell, 3 volts",
    "manufacturer": "MYOUNG",
    "lcsc": "C5239862",
    "mpn": "BS-02-A1AJ010",
    "package": "Holder, surface mount",
    "specs": {
      "Chemistry": "Lithium manganese, single use",
      "Voltage": "3 volts nominal",
      "Capacity": "About 225 milliamp hours",
      "Mounted by": "A real CR2032 holder, the part linked here"
    },
    "pros": [
      "Tiny and flat",
      "Runs a low power chip directly at 3 volts",
      "Long shelf life"
    ],
    "cons": [
      "Cannot deliver large current bursts",
      "Not rechargeable"
    ],
    "use": "Very low power devices that must last months, like a remote or a tag.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8589836660499247104",
    "lcscUrl": "https://www.lcsc.com/product-detail/Button-And-Strip-Battery-Connector_MYOUNG-MYOUNG-BS-02-A1AJ010.html",
    "preferred": false,
    "verified": true,
    "role": "source",
    "voltage": {
      "min": 2.0,
      "typ": 3.0,
      "max": 3.3
    },
    "current": {
      "active_mA": 0,
      "peak_mA": 20,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "power",
      "acdc": "dc"
    },
    "interfaces": [],
    "capacityMah": 225,
    "note": "The cell values are the standard CR2032 figures. The linked LCSC part is the holder you solder down."
  },
  {
    "id": "cat_cr1220_coin_cell_3_volts",
    "category": "battery",
    "subtype": "Coin cell",
    "name": "CR1220 coin cell, 3 volts",
    "manufacturer": "Lian Xin Technology",
    "lcsc": "C7498147",
    "mpn": "XDCR-1220-006",
    "package": "Holder, surface mount",
    "specs": {
      "Chemistry": "Lithium manganese, single use",
      "Voltage": "3 volts nominal",
      "Capacity": "About 40 milliamp hours",
      "Mounted by": "A real CR1220 holder, the part linked here"
    },
    "pros": [
      "Very small",
      "Good for a real time clock backup",
      "Long shelf life"
    ],
    "cons": [
      "Tiny capacity",
      "Very limited current"
    ],
    "use": "Backup power for a clock chip, or a very small low power tag.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8590905963052818432",
    "lcscUrl": "https://www.lcsc.com/product-detail/Battery-Connectors_Lian-Xin-Technology-Lian-Xin-Technology-XDCR-1220-006.html",
    "preferred": false,
    "verified": true,
    "role": "source",
    "voltage": {
      "min": 2.0,
      "typ": 3.0,
      "max": 3.3
    },
    "current": {
      "active_mA": 0,
      "peak_mA": 5,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "power",
      "acdc": "dc"
    },
    "interfaces": [],
    "capacityMah": 40,
    "note": "The cell values are the standard CR1220 figures. The linked LCSC part is the holder."
  },
  {
    "id": "cat_18650_lithium_ion_cell_3_7_volts",
    "category": "battery",
    "subtype": "Lithium ion",
    "name": "18650 lithium ion cell, 3.7 volts",
    "manufacturer": "MYOUNG",
    "lcsc": "C5290176",
    "mpn": "BH-18650-A1AJ005",
    "package": "Holder",
    "specs": {
      "Chemistry": "Lithium ion, rechargeable",
      "Voltage": "3.7 volts nominal, 4.2 full, 3.0 empty",
      "Capacity": "About 2500 to 3500 milliamp hours",
      "Mounted by": "A real 18650 holder, the part linked here"
    },
    "pros": [
      "Large capacity",
      "Rechargeable",
      "Can deliver strong current bursts"
    ],
    "cons": [
      "Needs a charge and protection circuit",
      "Bulky"
    ],
    "use": "Portable devices that need to run for hours and recharge.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8589839369181175808",
    "lcscUrl": "https://www.lcsc.com/product-detail/Battery-Connectors_MYOUNG-MYOUNG-BH-18650-A1AJ005.html",
    "preferred": false,
    "verified": true,
    "role": "source",
    "voltage": {
      "min": 3.0,
      "typ": 3.7,
      "max": 4.2
    },
    "current": {
      "active_mA": 0,
      "peak_mA": 3000,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "power",
      "acdc": "dc"
    },
    "interfaces": [],
    "capacityMah": 3000,
    "note": "The cell values are typical 18650 figures. The linked LCSC part is the holder. Add a protection circuit such as the DW01."
  },
  {
    "id": "cat_aaa_alkaline_cell_1_5_volts",
    "category": "battery",
    "subtype": "Alkaline",
    "name": "AAA alkaline cell, 1.5 volts",
    "manufacturer": "MYOUNG",
    "lcsc": "C6937107",
    "mpn": "MY-AAA-20-J",
    "package": "Clip",
    "specs": {
      "Chemistry": "Alkaline, single use",
      "Voltage": "1.5 volts each, so use two or three in series",
      "Capacity": "About 1000 milliamp hours",
      "Mounted by": "A real AAA clip, the part linked here"
    },
    "pros": [
      "Cheap and sold everywhere",
      "Easy for a user to replace",
      "Safe chemistry"
    ],
    "cons": [
      "Low voltage, you need several in series",
      "Heavier than a coin cell"
    ],
    "use": "Devices a normal user keeps running with shop bought batteries.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8590906288614289408",
    "lcscUrl": "https://www.lcsc.com/product-detail/Battery-Connectors_MYOUNG-MYOUNG-MY-AAA-20-J.html",
    "preferred": false,
    "verified": true,
    "role": "source",
    "voltage": {
      "min": 0.9,
      "typ": 1.5,
      "max": 1.6
    },
    "current": {
      "active_mA": 0,
      "peak_mA": 1000,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "power",
      "acdc": "dc"
    },
    "interfaces": [],
    "capacityMah": 1000,
    "note": "Two AAA cells give 3 volts, three give 4.5 volts. The linked LCSC part is one cell clip."
  },
  {
    "id": "cat_lithium_polymer_pouch_3_7_volts",
    "category": "battery",
    "subtype": "Lithium polymer",
    "name": "Lithium polymer pouch, 3.7 volts",
    "manufacturer": "Various, sourced as a finished cell",
    "lcsc": null,
    "mpn": null,
    "package": null,
    "specs": {
      "Chemistry": "Lithium polymer, rechargeable",
      "Voltage": "3.7 volts nominal, 4.2 full, 3.0 empty",
      "Capacity": "Common sizes from 300 to 2000 milliamp hours",
      "Connection": "A two pin connector, often the JST PH type"
    },
    "pros": [
      "Light and flat, fits slim devices",
      "Rechargeable",
      "Good energy for the size"
    ],
    "cons": [
      "Needs a charge and protection circuit",
      "Not a single LCSC stock part"
    ],
    "use": "Slim portable and wearable devices.",
    "datasheet": null,
    "lcscUrl": null,
    "preferred": false,
    "verified": false,
    "role": "source",
    "voltage": {
      "min": 3.0,
      "typ": 3.7,
      "max": 4.2
    },
    "current": {
      "active_mA": 0,
      "peak_mA": 2000,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "power",
      "acdc": "dc"
    },
    "interfaces": [],
    "capacityMah": 1000,
    "note": "Lithium polymer pouch cells are not a single LCSC catalogue part, so this entry is marked unverified. Add a charge and protection circuit such as the DW01, and connect through a two pin connector."
  },
  {
    "id": "cat_dw01_lithium_battery_protection",
    "category": "battery",
    "subtype": "Protection chip",
    "name": "DW01 lithium battery protection",
    "manufacturer": "Shenzhen Fuman Elec",
    "lcsc": "C2909013",
    "mpn": "DW01-A/J",
    "package": "SOT-23-6",
    "specs": {
      "Type": "Single cell lithium protection",
      "Guards against": "Over charge, over discharge, and short circuit",
      "Current": "Tiny standby draw",
      "Pairs with": "Two small protection transistors"
    },
    "pros": [
      "Protects a lithium cell for a few cents",
      "Tiny",
      "Industry standard"
    ],
    "cons": [
      "Single cell only",
      "Needs a matching pair of transistors"
    ],
    "use": "Protecting any single lithium ion or polymer cell from abuse.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588946919184084992",
    "lcscUrl": "https://www.lcsc.com/product-detail/Battery-Management_Shenzhen-Fuman-Elec-Shenzhen-Fuman-Elec-DW01-A-J.html",
    "preferred": false,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 1.5,
      "typ": 3.7,
      "max": 10.0
    },
    "current": {
      "active_mA": 0.001,
      "peak_mA": 0.003,
      "sleep_uA": 0.0007
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": []
  }
];
