/**
 * PCB Creation catalog: microcontrollers
 * Verified fields (LCSC number, manufacturer part number, datasheet and LCSC
 * links, package) come from the yaqwsx/jlcparts dataset. Pros, cons, use notes,
 * and typical current figures are curated. Entries marked verified:false have no
 * single confirmed LCSC part. Generated by scripts/build-catalog.py.
 */
export const microcontrollers = [
  {
    "id": "cat_rp2040",
    "category": "microcontroller",
    "subtype": "RISC, two cores",
    "name": "Raspberry Pi RP2040",
    "manufacturer": "Raspberry Pi",
    "lcsc": "C2040",
    "mpn": "RP2040",
    "package": "LQFN-56 7x7",
    "specs": {
      "Processor": "Two ARM Cortex-M0 plus cores at 133 megahertz",
      "Memory": "264 kilobytes of RAM, flash is external",
      "Input output pins": "30",
      "Analog inputs": "4 channels, 12 bit"
    },
    "pros": [
      "Very capable for the price with two cores",
      "Huge community and good documentation",
      "Flexible programmable input output"
    ],
    "cons": [
      "Needs an external flash chip to hold the program",
      "No built in wireless"
    ],
    "use": "A strong general purpose brain for robots, instruments, and Universal Serial Bus gadgets.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8550723933012836352",
    "lcscUrl": "https://www.lcsc.com/product-detail/Microcontrollers-MCU-MPU-SOC_Raspberry-Pi-Raspberry-Pi-RP2040.html",
    "preferred": false,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 1.8,
      "typ": 3.3,
      "max": 3.63
    },
    "current": {
      "active_mA": 40,
      "peak_mA": 120,
      "sleep_uA": 1000
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi",
      "uart",
      "usb"
    ]
  },
  {
    "id": "cat_esp32_c3fh4",
    "category": "microcontroller",
    "subtype": "Wireless, RISC",
    "name": "Espressif ESP32-C3FH4",
    "manufacturer": "Espressif Systems",
    "lcsc": "C2858491",
    "mpn": "ESP32-C3FH4",
    "package": "QFN-32-EP 5x5",
    "specs": {
      "Processor": "RISC five core at 160 megahertz",
      "Wireless": "Wi-Fi and Bluetooth Low Energy",
      "Memory": "4 megabytes of flash built in",
      "Input output pins": "22"
    },
    "pros": [
      "Wireless built in",
      "Flash is on chip so fewer parts",
      "Low cost for a connected design"
    ],
    "cons": [
      "Wireless bursts draw a large current spike",
      "Needs a clean 3.3 volt supply"
    ],
    "use": "Connected sensors and anything that reports over Wi-Fi or Bluetooth.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588919389660200960",
    "lcscUrl": "https://www.lcsc.com/product-detail/Microcontrollers-MCU-MPU-SOC_Espressif-Systems-Espressif-Systems-ESP32-C3FH4.html",
    "preferred": false,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 3.0,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 80,
      "peak_mA": 350,
      "sleep_uA": 5
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi",
      "uart",
      "usb",
      "wifi",
      "ble"
    ]
  },
  {
    "id": "cat_esp32_s3fn8",
    "category": "microcontroller",
    "subtype": "Wireless, dual core",
    "name": "Espressif ESP32-S3FN8",
    "manufacturer": "Espressif Systems",
    "lcsc": "C2913196",
    "mpn": "ESP32-S3FN8",
    "package": "QFN-56-EP 7x7",
    "specs": {
      "Processor": "Two Xtensa cores at 240 megahertz",
      "Wireless": "Wi-Fi and Bluetooth Low Energy",
      "Memory": "8 megabytes of flash built in",
      "Extras": "Vector instructions that help small machine learning tasks"
    },
    "pros": [
      "Fast with plenty of memory",
      "Wireless and native Universal Serial Bus",
      "Good for camera and audio work"
    ],
    "cons": [
      "Higher current than the C3",
      "More pins to route"
    ],
    "use": "Heavier connected projects such as cameras, audio, and on device inference.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588941122190389248",
    "lcscUrl": "https://www.lcsc.com/product-detail/WiFi-Modules_Espressif-Systems-Espressif-Systems-ESP32-S3FN8.html",
    "preferred": false,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 3.0,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 100,
      "peak_mA": 500,
      "sleep_uA": 10
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi",
      "uart",
      "usb",
      "wifi",
      "ble"
    ]
  },
  {
    "id": "cat_stm32f103c8t6",
    "category": "microcontroller",
    "subtype": "ARM, mainstream",
    "name": "ST STM32F103C8T6",
    "manufacturer": "STMicroelectronics",
    "lcsc": "C8734",
    "mpn": "STM32F103C8T6",
    "package": "LQFP-48 7x7",
    "specs": {
      "Processor": "ARM Cortex-M3 at 72 megahertz",
      "Memory": "64 kilobytes flash, 20 kilobytes RAM",
      "Input output pins": "37",
      "Analog inputs": "two 12 bit converters"
    },
    "pros": [
      "Very widely used, the blue pill chip",
      "Rich set of timers and interfaces",
      "On a Preferred parts list at the fab"
    ],
    "cons": [
      "Older core, modest memory",
      "Clones exist, buy from a known source"
    ],
    "use": "A dependable workhorse for motor control, instruments, and Universal Serial Bus devices.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8579708215774674944",
    "lcscUrl": "https://www.lcsc.com/product-detail/Microcontrollers-MCU-MPU-SOC_STMicroelectronics-STMicroelectronics-STM32F103C8T6.html",
    "preferred": true,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 2.0,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 50,
      "peak_mA": 80,
      "sleep_uA": 20
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi",
      "uart",
      "usb",
      "can"
    ]
  },
  {
    "id": "cat_stm32f030f4p6",
    "category": "microcontroller",
    "subtype": "ARM, low cost",
    "name": "ST STM32F030F4P6",
    "manufacturer": "STMicroelectronics",
    "lcsc": "C32908",
    "mpn": "STM32F030F4P6",
    "package": "TSSOP-20",
    "specs": {
      "Processor": "ARM Cortex-M0 at 48 megahertz",
      "Memory": "16 kilobytes flash, 4 kilobytes RAM",
      "Input output pins": "15",
      "Package": "A small 20 pin part"
    },
    "pros": [
      "Cheap and tiny",
      "Easy to hand solder",
      "Enough for simple control jobs"
    ],
    "cons": [
      "Little memory",
      "No Universal Serial Bus"
    ],
    "use": "Small, cost sensitive boards that need a real microcontroller.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8579708278022475776",
    "lcscUrl": "https://www.lcsc.com/product-detail/Microcontrollers-MCU-MPU-SOC_STMicroelectronics-STMicroelectronics-STM32F030F4P6.html",
    "preferred": false,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 2.4,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 20,
      "peak_mA": 40,
      "sleep_uA": 10
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi",
      "uart"
    ]
  },
  {
    "id": "cat_stm32g030f6p6tr",
    "category": "microcontroller",
    "subtype": "ARM, modern low cost",
    "name": "ST STM32G030F6P6",
    "manufacturer": "STMicroelectronics",
    "lcsc": "C529330",
    "mpn": "STM32G030F6P6TR",
    "package": "TSSOP-20",
    "specs": {
      "Processor": "ARM Cortex-M0 plus at 64 megahertz",
      "Memory": "32 kilobytes flash, 8 kilobytes RAM",
      "Input output pins": "17",
      "Analog inputs": "12 bit converter"
    },
    "pros": [
      "Newer core, better value than the F030",
      "Low power modes are strong",
      "Tiny 20 pin package"
    ],
    "cons": [
      "Limited pin count",
      "No Universal Serial Bus"
    ],
    "use": "Modern replacement for the F030 in small low power designs.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8568762048140279808",
    "lcscUrl": "https://www.lcsc.com/product-detail/Microcontrollers-MCU-MPU-SOC_STMicroelectronics-STMicroelectronics-STM32G030F6P6TR.html",
    "preferred": false,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 2.0,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 15,
      "peak_mA": 40,
      "sleep_uA": 5
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi",
      "uart"
    ]
  },
  {
    "id": "cat_atmega328p_au",
    "category": "microcontroller",
    "subtype": "AVR, beginner friendly",
    "name": "Microchip ATmega328P",
    "manufacturer": "Microchip Tech",
    "lcsc": "C14877",
    "mpn": "ATMEGA328P-AU",
    "package": "TQFP-32 7x7",
    "specs": {
      "Processor": "8 bit AVR at up to 20 megahertz",
      "Memory": "32 kilobytes flash, 2 kilobytes RAM",
      "Input output pins": "23",
      "Analog inputs": "six to eight 10 bit channels"
    },
    "pros": [
      "The Arduino Uno chip, very easy to start with",
      "Tolerant 5 volt design",
      "Enormous example base"
    ],
    "cons": [
      "Slow and small by modern standards",
      "8 bit only"
    ],
    "use": "Beginner boards and anything that wants the Arduino Uno experience.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8586171945553838081",
    "lcscUrl": "https://www.lcsc.com/product-detail/Microcontrollers-MCU-MPU-SOC_Microchip-Tech-Microchip-Tech-ATMEGA328P-AU.html",
    "preferred": true,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 1.8,
      "typ": 5.0,
      "max": 5.5
    },
    "current": {
      "active_mA": 12,
      "peak_mA": 25,
      "sleep_uA": 1
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi",
      "uart"
    ]
  },
  {
    "id": "cat_atmega32u4_au",
    "category": "microcontroller",
    "subtype": "AVR, native USB",
    "name": "Microchip ATmega32U4",
    "manufacturer": "Microchip Tech",
    "lcsc": "C44854",
    "mpn": "ATMEGA32U4-AU",
    "package": "QFP-44 10x10",
    "specs": {
      "Processor": "8 bit AVR at 16 megahertz",
      "Memory": "32 kilobytes flash, 2.5 kilobytes RAM",
      "Special": "Universal Serial Bus built into the chip",
      "Input output pins": "26"
    },
    "pros": [
      "Talks Universal Serial Bus with no extra chip",
      "Used in the Arduino Leonardo and Micro",
      "Good for keyboards and input devices"
    ],
    "cons": [
      "Still 8 bit and slow",
      "Universal Serial Bus wants a steady 5 volt or careful 3.3 volt design"
    ],
    "use": "Custom keyboards, game controllers, and other Universal Serial Bus input devices.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8586181634466570240",
    "lcscUrl": "https://www.lcsc.com/product-detail/Microcontrollers-MCU-MPU-SOC_Microchip-Tech-Microchip-Tech-ATMEGA32U4-AU.html",
    "preferred": false,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 2.7,
      "typ": 5.0,
      "max": 5.5
    },
    "current": {
      "active_mA": 20,
      "peak_mA": 40,
      "sleep_uA": 10
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi",
      "uart",
      "usb"
    ]
  },
  {
    "id": "cat_attiny85v_10su",
    "category": "microcontroller",
    "subtype": "AVR, tiny",
    "name": "Microchip ATtiny85",
    "manufacturer": "Microchip Tech",
    "lcsc": "C152192",
    "mpn": "ATTINY85V-10SU",
    "package": "SOIC-8-208mil",
    "specs": {
      "Processor": "8 bit AVR",
      "Memory": "8 kilobytes flash, 512 bytes RAM",
      "Input output pins": "6",
      "Package": "A small 8 pin part"
    },
    "pros": [
      "Very small and cheap",
      "Sips power, good on a coin cell",
      "Simple to program"
    ],
    "cons": [
      "Only six input output pins",
      "Tiny memory"
    ],
    "use": "Single job gadgets like a blinker, a tiny sensor, or a power switch.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588883456827146240",
    "lcscUrl": "https://www.lcsc.com/product-detail/Microcontrollers-MCU-MPU-SOC_Microchip-Tech-Microchip-Tech-ATTINY85V-10SU.html",
    "preferred": false,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 1.8,
      "typ": 3.3,
      "max": 5.5
    },
    "current": {
      "active_mA": 5,
      "peak_mA": 12,
      "sleep_uA": 1
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi"
    ]
  },
  {
    "id": "cat_ch32v003f4u6",
    "category": "microcontroller",
    "subtype": "RISC, ultra low cost",
    "name": "WCH CH32V003F4U6",
    "manufacturer": "WCH Jiangsu Qin Heng",
    "lcsc": "C5299908",
    "mpn": "CH32V003F4U6",
    "package": "QFN-20 3X3",
    "specs": {
      "Processor": "RISC core at 48 megahertz",
      "Memory": "16 kilobytes flash, 2 kilobytes RAM",
      "Input output pins": "18",
      "Note": "One of the cheapest real microcontrollers"
    },
    "pros": [
      "Extremely cheap",
      "Runs from 3.3 to 5 volts",
      "Surprisingly quick for the price"
    ],
    "cons": [
      "Smaller tool ecosystem",
      "Limited memory"
    ],
    "use": "High volume or throwaway boards where unit cost matters most.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8618867492358148096",
    "lcscUrl": "https://www.lcsc.com/product-detail/Microcontroller-Units-MCUs-MPUs-SOCs_WCHJiangsu-Qin-Heng-WCHJiangsu-Qin-Heng-CH32V003F4U6.html",
    "preferred": false,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 3.0,
      "typ": 3.3,
      "max": 5.0
    },
    "current": {
      "active_mA": 8,
      "peak_mA": 20,
      "sleep_uA": 10
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi",
      "uart"
    ]
  }
];
