/**
 * PCB Creation catalog: motors
 * Verified fields (LCSC number, manufacturer part number, datasheet and LCSC
 * links, package) come from the yaqwsx/jlcparts dataset. Pros, cons, use notes,
 * and typical current figures are curated. Entries marked verified:false have no
 * single confirmed LCSC part. Generated by scripts/build-catalog.py.
 */
export const motors = [
  {
    "id": "cat_z3oc1t8219731",
    "category": "motor",
    "subtype": "Vibration",
    "name": "KOTL coin vibration motor, surface mount",
    "manufacturer": "KOTL",
    "lcsc": "C2894731",
    "mpn": "Z3OC1T8219731",
    "package": null,
    "specs": {
      "Type": "Vibrating offset weight motor",
      "Rated voltage": "2.7 volts",
      "Rated current": "85 milliamps",
      "Mounting": "Surface mount",
      "Speed": "About 14000 turns per minute"
    },
    "pros": [
      "Tiny and solders flat to the board",
      "Cheap",
      "Simple haptic buzz"
    ],
    "cons": [
      "Needs a driver transistor and a flyback diode",
      "Startup current is higher than the rating"
    ],
    "use": "Haptic buzz feedback in a small handheld device.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588920162417823744",
    "lcscUrl": "https://www.lcsc.com/product-detail/Vibration-Motor_KOTL-KOTL-Z3OC1T8219731.html",
    "preferred": false,
    "verified": true,
    "role": "actuator",
    "voltage": {
      "min": 2.5,
      "typ": 2.7,
      "max": 3.3
    },
    "current": {
      "active_mA": 85,
      "peak_mA": 150,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "power",
      "acdc": "dc"
    },
    "interfaces": [],
    "inductive": true,
    "driverLcsc": "C88224"
  },
  {
    "id": "cat_lcm1027a2445f",
    "category": "motor",
    "subtype": "Vibration",
    "name": "LEADER flat vibration motor, leaded",
    "manufacturer": "LEADER",
    "lcsc": "C2759984",
    "mpn": "LCM1027A2445F",
    "package": null,
    "specs": {
      "Type": "Flat coin vibration motor",
      "Rated voltage": "3 volts",
      "Rated current": "80 milliamps",
      "Mounting": "Wire leads",
      "Diameter": "About 9 millimetres"
    },
    "pros": [
      "Classic pancake buzzer",
      "Easy to glue in place",
      "Cheap"
    ],
    "cons": [
      "Wire leads, not board mount",
      "Needs a driver and a flyback diode"
    ],
    "use": "Buzz alerts in wearables and remote controls.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8589042212931293184",
    "lcscUrl": "https://www.lcsc.com/product-detail/Vibration-Motors_LEADER-LEADER-LCM1027A2445F.html",
    "preferred": false,
    "verified": true,
    "role": "actuator",
    "voltage": {
      "min": 2.5,
      "typ": 3.0,
      "max": 3.6
    },
    "current": {
      "active_mA": 80,
      "peak_mA": 150,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "power",
      "acdc": "dc"
    },
    "interfaces": [],
    "inductive": true,
    "driverLcsc": "C88224"
  },
  {
    "id": "cat_tb6612fng_o_c_8_el",
    "category": "motor",
    "subtype": "Driver chip",
    "name": "Toshiba TB6612FNG dual motor driver",
    "manufacturer": "TOSHIBA",
    "lcsc": "C88224",
    "mpn": "TB6612FNG(O,C,8,EL",
    "package": "SSOP-24-208mil",
    "specs": {
      "Type": "Two channel H bridge driver",
      "Motor supply": "Up to 13.5 volts",
      "Current": "1.2 amps each channel, 3.2 amps peak",
      "Control": "Direction and speed pins, plus speed control input"
    },
    "pros": [
      "Drives two motors or one stepper",
      "Efficient, runs cool",
      "Built in protection"
    ],
    "cons": [
      "Needs both a logic supply and a motor supply",
      "Tiny pin pitch"
    ],
    "use": "The go to driver for two small motors or one bipolar stepper.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588881773258686464",
    "lcscUrl": "https://www.lcsc.com/search?q=C88224",
    "preferred": false,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 2.5,
      "typ": 3.3,
      "max": 5.5
    },
    "current": {
      "active_mA": 2,
      "peak_mA": 5,
      "sleep_uA": 1
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": []
  },
  {
    "id": "cat_l9110s",
    "category": "motor",
    "subtype": "Driver chip",
    "name": "Mixic L9110S dual motor driver",
    "manufacturer": "Mixic",
    "lcsc": "C513306",
    "mpn": "L9110S",
    "package": "SOP-8",
    "specs": {
      "Type": "Two channel H bridge driver",
      "Supply": "2.5 to 12 volts",
      "Current": "About 800 milliamps each channel",
      "Control": "Two pins per channel"
    },
    "pros": [
      "Very cheap and simple",
      "Single supply",
      "Easy to wire"
    ],
    "cons": [
      "Lower current than the TB6612",
      "Less efficient"
    ],
    "use": "Cheap and cheerful driving of small motors.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588905115629993984",
    "lcscUrl": "https://www.lcsc.com/search?q=C513306",
    "preferred": false,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 2.5,
      "typ": 5.0,
      "max": 12.0
    },
    "current": {
      "active_mA": 2,
      "peak_mA": 4,
      "sleep_uA": 1
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": []
  },
  {
    "id": "cat_at8236",
    "category": "motor",
    "subtype": "Driver chip",
    "name": "Zhongkewei AT8236 motor driver",
    "manufacturer": "ZHONGKEWEI",
    "lcsc": "C2827823",
    "mpn": "AT8236",
    "package": "ESOP-8",
    "specs": {
      "Type": "Single H bridge driver",
      "Current": "High, several amps peak",
      "Control": "Direction and speed pins",
      "Stock": "Very well stocked and cheap"
    },
    "pros": [
      "Handles higher current than most cheap drivers",
      "Plentiful and low cost",
      "Built in protection"
    ],
    "cons": [
      "One motor per chip",
      "Needs good heat sinking at high current"
    ],
    "use": "Driving one larger brushed motor with plenty of current.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588894460923428864",
    "lcscUrl": "https://www.lcsc.com/search?q=C2827823",
    "preferred": false,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 2.5,
      "typ": 5.0,
      "max": 11.0
    },
    "current": {
      "active_mA": 2,
      "peak_mA": 7,
      "sleep_uA": 1
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": []
  },
  {
    "id": "cat_brushed_dc_motor_small",
    "category": "motor",
    "subtype": "Brushed direct current",
    "name": "Brushed DC motor, small",
    "manufacturer": "Various",
    "lcsc": null,
    "mpn": null,
    "package": null,
    "specs": {
      "Type": "Plain two wire brushed motor",
      "Voltage": "Commonly 3 to 9 volts",
      "Running current": "A few hundred milliamps",
      "Stall current": "Up to about 1.5 amps"
    },
    "pros": [
      "Cheap and simple",
      "Easy to drive with an H bridge",
      "Plenty of choice"
    ],
    "cons": [
      "Brushes wear out",
      "Stall current is high, plan the supply for it"
    ],
    "use": "Wheels, fans, and pumps on small robots.",
    "datasheet": null,
    "lcscUrl": null,
    "preferred": false,
    "verified": false,
    "role": "actuator",
    "voltage": {
      "min": 3,
      "typ": 6,
      "max": 9
    },
    "current": {
      "active_mA": 300,
      "peak_mA": 1500,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "power",
      "acdc": "dc"
    },
    "interfaces": [],
    "inductive": true,
    "driverLcsc": "C88224",
    "note": "A bare motor is not a single LCSC part, so this is unverified. Drive it through the linked driver and add a flyback diode."
  },
  {
    "id": "cat_geared_dc_motor",
    "category": "motor",
    "subtype": "Geared direct current",
    "name": "Geared DC motor",
    "manufacturer": "Various",
    "lcsc": null,
    "mpn": null,
    "package": null,
    "specs": {
      "Type": "Brushed motor with a gearbox",
      "Voltage": "Commonly 3 to 6 volts",
      "Result": "Slower turning with much more turning force"
    },
    "pros": [
      "High turning force at low speed",
      "Good for driving wheels",
      "Cheap as a kit motor"
    ],
    "cons": [
      "Gearbox adds size",
      "Stall current is still high"
    ],
    "use": "Drive wheels on a small rover or a moving mechanism.",
    "datasheet": null,
    "lcscUrl": null,
    "preferred": false,
    "verified": false,
    "role": "actuator",
    "voltage": {
      "min": 3,
      "typ": 6,
      "max": 6
    },
    "current": {
      "active_mA": 150,
      "peak_mA": 1000,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "power",
      "acdc": "dc"
    },
    "interfaces": [],
    "inductive": true,
    "driverLcsc": "C88224",
    "note": "A bare motor is not a single LCSC part, so this is unverified. Drive it through the linked driver and add a flyback diode."
  },
  {
    "id": "cat_stepper_motor_bipolar",
    "category": "motor",
    "subtype": "Stepper",
    "name": "Stepper motor, bipolar",
    "manufacturer": "Various",
    "lcsc": null,
    "mpn": null,
    "package": null,
    "specs": {
      "Type": "Two coil bipolar stepper",
      "Voltage": "Commonly 5 to 12 volts",
      "Control": "Steps in fixed angles, holds position"
    },
    "pros": [
      "Precise position without a sensor",
      "Strong holding force",
      "Repeatable moves"
    ],
    "cons": [
      "Needs a stepper driver",
      "Draws current even when still"
    ],
    "use": "Precise positioning, such as a small 3D printer axis or a dial.",
    "datasheet": null,
    "lcscUrl": null,
    "preferred": false,
    "verified": false,
    "role": "actuator",
    "voltage": {
      "min": 5,
      "typ": 5,
      "max": 12
    },
    "current": {
      "active_mA": 240,
      "peak_mA": 800,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "power",
      "acdc": "dc"
    },
    "interfaces": [],
    "inductive": true,
    "driverLcsc": "C88224",
    "note": "A bare motor is not a single LCSC part, so this is unverified. Drive a small bipolar stepper with the linked dual driver."
  },
  {
    "id": "cat_hobby_servo_motor",
    "category": "motor",
    "subtype": "Servo",
    "name": "Hobby servo motor",
    "manufacturer": "Various",
    "lcsc": null,
    "mpn": null,
    "package": null,
    "specs": {
      "Type": "Geared motor with built in control",
      "Voltage": "4.8 to 6 volts",
      "Control": "A single timing signal sets the angle",
      "Built in": "Its own driver and position sensor"
    },
    "pros": [
      "Just three wires, easy to use",
      "Holds an angle by itself",
      "No extra driver chip"
    ],
    "cons": [
      "Limited to about 180 degrees of travel",
      "Current spikes when it moves, buffer the supply"
    ],
    "use": "Moving an arm, a flap, or a steering linkage to a set angle.",
    "datasheet": null,
    "lcscUrl": null,
    "preferred": false,
    "verified": false,
    "role": "actuator",
    "voltage": {
      "min": 4.8,
      "typ": 5.0,
      "max": 6.0
    },
    "current": {
      "active_mA": 200,
      "peak_mA": 700,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "power",
      "acdc": "dc"
    },
    "interfaces": [
      "pwm"
    ],
    "inductive": true,
    "note": "A finished servo is not a single LCSC part, so this is unverified. It needs only a timing signal from a pin and a solid 5 volt supply."
  },
  {
    "id": "cat_brushless_dc_motor_small",
    "category": "motor",
    "subtype": "Brushless direct current",
    "name": "Brushless DC motor, small",
    "manufacturer": "Various",
    "lcsc": null,
    "mpn": null,
    "package": null,
    "specs": {
      "Type": "Three phase brushless motor",
      "Voltage": "Commonly 7 to 12 volts",
      "Needs": "A three phase electronic speed controller"
    },
    "pros": [
      "Efficient and long lived, no brushes",
      "High speed",
      "Smooth running"
    ],
    "cons": [
      "Needs a special three phase driver",
      "More complex to control"
    ],
    "use": "Drones, fans, and anything that spins fast for a long time.",
    "datasheet": null,
    "lcscUrl": null,
    "preferred": false,
    "verified": false,
    "role": "actuator",
    "voltage": {
      "min": 7,
      "typ": 12,
      "max": 12
    },
    "current": {
      "active_mA": 500,
      "peak_mA": 3000,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "power",
      "acdc": "dc"
    },
    "interfaces": [],
    "inductive": true,
    "note": "A bare brushless motor is not a single LCSC part, so this is unverified. It needs a three phase electronic speed controller, which is more than a simple H bridge."
  }
];
