/**
 * PCB Creation catalog: screens
 * Verified fields (LCSC number, manufacturer part number, datasheet and LCSC
 * links, package) come from the yaqwsx/jlcparts dataset. Pros, cons, use notes,
 * and typical current figures are curated. Entries marked verified:false have no
 * single confirmed LCSC part. Generated by scripts/build-catalog.py.
 */
export const screens = [
  {
    "id": "cat_hs91l02w2c01",
    "category": "screen",
    "subtype": "OLED",
    "name": "0.91 inch OLED 128 by 32",
    "manufacturer": "HS",
    "lcsc": "C5248081",
    "mpn": "HS91L02W2C01",
    "package": null,
    "specs": {
      "Type": "Self lit OLED, white",
      "Resolution": "128 by 32 pixels",
      "Driver": "SSD1306",
      "Interface": "I2C"
    },
    "pros": [
      "Crisp self lit display, no backlight",
      "Only two signal wires on I2C",
      "Cheap"
    ],
    "cons": [
      "Small, text only really",
      "Single I2C address"
    ],
    "use": "A tiny status readout for a sensor or a tool.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8590904885750030336",
    "lcscUrl": "https://www.lcsc.com/search?q=C5248081",
    "preferred": false,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 3.0,
      "typ": 3.3,
      "max": 3.3
    },
    "current": {
      "active_mA": 10,
      "peak_mA": 20,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_hs96l03w2c03",
    "category": "screen",
    "subtype": "OLED",
    "name": "0.96 inch OLED 128 by 64",
    "manufacturer": "HS",
    "lcsc": "C5248080",
    "mpn": "HS96L03W2C03",
    "package": null,
    "specs": {
      "Type": "Self lit OLED, white",
      "Resolution": "128 by 64 pixels",
      "Driver": "SSD1315, works like the SSD1306",
      "Interface": "I2C"
    },
    "pros": [
      "The most common hobby OLED",
      "Good size for menus and small graphics",
      "Two wires on I2C"
    ],
    "cons": [
      "Still small",
      "One I2C address"
    ],
    "use": "The default little screen for menus, readouts, and graphs.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8589838468881670144",
    "lcscUrl": "https://www.lcsc.com/search?q=C5248080",
    "preferred": false,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 3.0,
      "typ": 3.3,
      "max": 3.3
    },
    "current": {
      "active_mA": 15,
      "peak_mA": 25,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_hs13l03w2c01",
    "category": "screen",
    "subtype": "OLED",
    "name": "1.3 inch OLED 128 by 64",
    "manufacturer": "HS",
    "lcsc": "C7465997",
    "mpn": "HS13L03W2C01",
    "package": null,
    "specs": {
      "Type": "Self lit OLED, white",
      "Resolution": "128 by 64 pixels",
      "Driver": "SH1106",
      "Interface": "I2C"
    },
    "pros": [
      "Bigger and easier to read",
      "Self lit, high contrast",
      "Two wires on I2C"
    ],
    "cons": [
      "SH1106 needs a small code tweak versus the SSD1306",
      "Costs a little more"
    ],
    "use": "A larger, more readable status screen.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8603058573346033664",
    "lcscUrl": "https://www.lcsc.com/search?q=C7465997",
    "preferred": false,
    "verified": true,
    "role": "controller",
    "voltage": {
      "min": 3.0,
      "typ": 3.3,
      "max": 3.3
    },
    "current": {
      "active_mA": 18,
      "peak_mA": 30,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  }
];
