/**
 * PCB Creation catalog: sensors
 * Verified fields (LCSC number, manufacturer part number, datasheet and LCSC
 * links, package) come from the yaqwsx/jlcparts dataset. Pros, cons, use notes,
 * and typical current figures are curated. Entries marked verified:false have no
 * single confirmed LCSC part. Generated by scripts/build-catalog.py.
 */
export const sensors = [
  {
    "id": "cat_bh1750fvi_tr",
    "category": "sensor",
    "subtype": "Light",
    "name": "ROHM BH1750FVI ambient light sensor",
    "manufacturer": "ROHM Semicon",
    "lcsc": "C78960",
    "mpn": "BH1750FVI-TR",
    "package": "WSOF-6",
    "specs": {
      "Measures": "Ambient light in lux",
      "Range": "1 to 65535 lux",
      "Interface": "I2C",
      "Output": "Direct lux reading, no maths needed"
    },
    "pros": [
      "Reads straight out in lux",
      "Cheap and very common",
      "Low current"
    ],
    "cons": [
      "Fixed addresses, only two on one bus",
      "No interrupt pin"
    ],
    "use": "Screen brightness control and simple day or night sensing.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588881948718870528",
    "lcscUrl": "https://www.lcsc.com/product-detail/Ambient-Light-Sensors_ROHM-Semicon-ROHM-Semicon-BH1750FVI-TR.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.4,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 0.12,
      "peak_mA": 0.2,
      "sleep_uA": 0.001
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_veml7700_tr",
    "category": "sensor",
    "subtype": "Light",
    "name": "Vishay VEML7700 ambient light sensor",
    "manufacturer": "Vishay Intertech",
    "lcsc": "C504893",
    "mpn": "VEML7700-TR",
    "package": "SMD-4P",
    "specs": {
      "Measures": "Ambient light in lux",
      "Range": "0 to about 120000 lux",
      "Interface": "I2C",
      "Response": "Close to the human eye"
    },
    "pros": [
      "Very wide brightness range",
      "Response matched to the eye",
      "Good accuracy"
    ],
    "cons": [
      "Needs a clear window above it",
      "Slightly more setup than the BH1750"
    ],
    "use": "Accurate light metering across dim rooms to bright sun.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8589835238374203392",
    "lcscUrl": "https://www.lcsc.com/product-detail/Ambient-Light-Sensors_Vishay-Intertech-Vishay-Intertech-VEML7700-TR.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.5,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 0.5,
      "peak_mA": 1.0,
      "sleep_uA": 0.001
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_temt6000x01",
    "category": "sensor",
    "subtype": "Light",
    "name": "Vishay TEMT6000 light phototransistor",
    "manufacturer": "Vishay Intertech",
    "lcsc": "C94098",
    "mpn": "TEMT6000X01",
    "package": "1206",
    "specs": {
      "Measures": "Ambient light, analog",
      "Output": "A current that rises with brightness",
      "Interface": "Analog, read with an analog input",
      "Response": "Close to the human eye"
    },
    "pros": [
      "Dead simple, one analog pin",
      "Very cheap",
      "No bus address to manage"
    ],
    "cons": [
      "Needs an analog input and a load resistor",
      "Not calibrated in lux"
    ],
    "use": "A rough cheap light level on any chip with an analog input.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588907152199467008",
    "lcscUrl": "https://www.lcsc.com/product-detail/Ambient-Light-Sensors_Vishay-Intertech-Vishay-Intertech-TEMT6000X01.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.5,
      "typ": 3.3,
      "max": 5.5
    },
    "current": {
      "active_mA": 0.02,
      "peak_mA": 0.1,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "analog"
    ]
  },
  {
    "id": "cat_ltr_303als_01",
    "category": "sensor",
    "subtype": "Light",
    "name": "Lite-On LTR-303ALS digital light sensor",
    "manufacturer": "Lite On",
    "lcsc": "C364577",
    "mpn": "LTR-303ALS-01",
    "package": "DFN-6 2x2",
    "specs": {
      "Measures": "Ambient light in lux",
      "Interface": "I2C",
      "Extra": "Has an interrupt pin and window comparison"
    },
    "pros": [
      "Interrupt pin wakes the chip on a light change",
      "Small package",
      "Low current"
    ],
    "cons": [
      "Lower stock at times",
      "Tiny part, harder to hand solder"
    ],
    "use": "Battery designs that should sleep until the light changes.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8564043622443483136",
    "lcscUrl": "https://www.lcsc.com/product-detail/Ambient-Light-Sensors_Lite-On-Lite-On-LTR-303ALS-01.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.4,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 0.2,
      "peak_mA": 0.3,
      "sleep_uA": 0.001
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_als_pt19_315c_l177_tr8",
    "category": "sensor",
    "subtype": "Light",
    "name": "Everlight ALS-PT19 light phototransistor",
    "manufacturer": "Everlight Elec",
    "lcsc": "C146233",
    "mpn": "ALS-PT19-315C/L177/TR8",
    "package": "0603",
    "specs": {
      "Measures": "Ambient light, analog",
      "Output": "A current that rises with brightness",
      "Interface": "Analog",
      "Size": "A very small surface mount part"
    },
    "pros": [
      "Tiny and very cheap",
      "Simple analog output",
      "Popular and well stocked"
    ],
    "cons": [
      "Needs an analog input and a load resistor",
      "Not calibrated in lux"
    ],
    "use": "Compact boards that want a cheap light reading from an analog pin.",
    "datasheet": "https://www.everlight.com.cn/wp-content/plugins/ItemRelationship/product_files/pdf/ALS-PT19-315C-L177-TR8_V8.pdf",
    "lcscUrl": "https://www.lcsc.com/search?q=C146233",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.5,
      "typ": 3.3,
      "max": 5.5
    },
    "current": {
      "active_mA": 0.02,
      "peak_mA": 0.1,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "analog"
    ]
  },
  {
    "id": "cat_ds18b20",
    "category": "sensor",
    "subtype": "Temperature",
    "name": "Maxim DS18B20 temperature sensor",
    "manufacturer": "Analog Devices Inc Maxim Integrated",
    "lcsc": "C9753",
    "mpn": "DS18B20+",
    "package": "TO-92",
    "specs": {
      "Measures": "Temperature from minus 55 to 125 degrees C",
      "Accuracy": "Half a degree from minus 10 to 85",
      "Interface": "One wire, many on a single pin",
      "Output": "Direct digital reading"
    },
    "pros": [
      "Many sensors share one pin",
      "Long cable runs work well",
      "Each chip has a unique address"
    ],
    "cons": [
      "Conversion is slow, up to 750 milliseconds",
      "Needs a pull-up on the data line"
    ],
    "use": "Temperature probes on long wires, like a fridge or a fish tank.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588887319054704640",
    "lcscUrl": "https://www.lcsc.com/product-detail/Temperature-Sensors_Analog-Devices-Inc.-Maxim-Integrated-Analog-Devices-Inc.-Maxim-Integrated-DS18B20%2B.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 3.0,
      "typ": 3.3,
      "max": 5.5
    },
    "current": {
      "active_mA": 1.0,
      "peak_mA": 1.5,
      "sleep_uA": 0.001
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "onewire"
    ]
  },
  {
    "id": "cat_lm75bd_118",
    "category": "sensor",
    "subtype": "Temperature",
    "name": "NXP LM75B temperature sensor",
    "manufacturer": "NXP Semicon",
    "lcsc": "C34565",
    "mpn": "LM75BD,118",
    "package": "SOIC-8",
    "specs": {
      "Measures": "Temperature from minus 55 to 125 degrees C",
      "Accuracy": "Two degrees",
      "Interface": "I2C",
      "Extra": "Has an over temperature alarm pin"
    },
    "pros": [
      "Simple and cheap",
      "Alarm pin for a thermostat",
      "Up to eight on one bus"
    ],
    "cons": [
      "Two degree accuracy is modest",
      "Surface mount only"
    ],
    "use": "Board temperature watch and simple thermostat alarms.",
    "datasheet": "https://www.nxp.com.cn/docs/en/data-sheet/LM75B.pdf",
    "lcscUrl": "https://www.lcsc.com/product-detail/Temperature-Sensors_NXP-Semicon-NXP-Semicon-LM75BD%2C118.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.7,
      "typ": 3.3,
      "max": 5.5
    },
    "current": {
      "active_mA": 0.3,
      "peak_mA": 0.5,
      "sleep_uA": 0.001
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_tmp112aidrlr",
    "category": "sensor",
    "subtype": "Temperature",
    "name": "TI TMP112 temperature sensor",
    "manufacturer": "Texas Instruments",
    "lcsc": "C28927",
    "mpn": "TMP112AIDRLR",
    "package": "SOT-563",
    "specs": {
      "Measures": "Temperature from minus 40 to 125 degrees C",
      "Accuracy": "Half a degree",
      "Interface": "I2C",
      "Current": "Very low, about 10 microamps"
    },
    "pros": [
      "Very low power",
      "Good accuracy",
      "Tiny package"
    ],
    "cons": [
      "Small part, harder to solder",
      "Needs a clean supply"
    ],
    "use": "Low power and battery designs that still want good accuracy.",
    "datasheet": "https://www.ti.com/cn/lit/gpn/tmp112",
    "lcscUrl": "https://www.lcsc.com/product-detail/Temperature-Sensors_Texas-Instruments-Texas-Instruments-TMP112AIDRLR.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 1.4,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 0.01,
      "peak_mA": 0.03,
      "sleep_uA": 0.001
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_tmp102aidrlr",
    "category": "sensor",
    "subtype": "Temperature",
    "name": "TI TMP102 temperature sensor",
    "manufacturer": "Texas Instruments",
    "lcsc": "C99269",
    "mpn": "TMP102AIDRLR",
    "package": "SOT-563",
    "specs": {
      "Measures": "Temperature from minus 40 to 125 degrees C",
      "Accuracy": "Half a degree typical",
      "Interface": "I2C",
      "Current": "About 10 microamps"
    },
    "pros": [
      "Low power",
      "Cheap and common",
      "Small footprint"
    ],
    "cons": [
      "Tiny part",
      "Address options are limited"
    ],
    "use": "General temperature sensing on a tight power budget.",
    "datasheet": "https://www.ti.com/cn/lit/gpn/tmp102",
    "lcscUrl": "https://www.lcsc.com/product-detail/Temperature-Sensors_Texas-Instruments-Texas-Instruments-TMP102AIDRLR.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 1.4,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 0.01,
      "peak_mA": 0.03,
      "sleep_uA": 0.001
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_mcp9808_e_ms",
    "category": "sensor",
    "subtype": "Temperature",
    "name": "Microchip MCP9808 temperature sensor",
    "manufacturer": "Microchip Tech",
    "lcsc": "C94847",
    "mpn": "MCP9808-E/MS",
    "package": "MSOP-8",
    "specs": {
      "Measures": "Temperature from minus 40 to 125 degrees C",
      "Accuracy": "A quarter of a degree, the best here",
      "Interface": "I2C",
      "Extra": "Programmable alarm window"
    },
    "pros": [
      "Highest accuracy in this group",
      "Alarm with adjustable limits",
      "Eight addresses on one bus"
    ],
    "cons": [
      "Costs more than the others",
      "Surface mount only"
    ],
    "use": "When you need the most accurate temperature reading.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588882201379278848",
    "lcscUrl": "https://www.lcsc.com/product-detail/Temperature-Sensors_Microchip-Tech-Microchip-Tech-MCP9808-E-MS.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.7,
      "typ": 3.3,
      "max": 5.5
    },
    "current": {
      "active_mA": 0.2,
      "peak_mA": 0.4,
      "sleep_uA": 0.001
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_ncp03wf104f05rl",
    "category": "sensor",
    "subtype": "Temperature",
    "name": "Murata NCP03 100k thermistor",
    "manufacturer": "Murata Electronics",
    "lcsc": "C91635",
    "mpn": "NCP03WF104F05RL",
    "package": "0201",
    "specs": {
      "Measures": "Temperature, analog",
      "Type": "A resistor that changes with heat, 100 kilohms at 25 degrees C",
      "Interface": "Read with a divider and an analog input",
      "Cost": "A few cents"
    },
    "pros": [
      "The cheapest way to sense temperature",
      "Tiny and rugged",
      "No bus or address"
    ],
    "cons": [
      "Needs a divider resistor and a maths step",
      "Less accurate without calibration"
    ],
    "use": "Cheap temperature sensing, and watching a hot part like a regulator.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8589808042864123904",
    "lcscUrl": "https://www.lcsc.com/product-detail/NTC-Thermistors_muRata-muRata-NCP03WF104F05RL.html",
    "preferred": false,
    "verified": true,
    "role": "passive",
    "voltage": {
      "min": 0,
      "typ": 0,
      "max": 0
    },
    "current": {
      "active_mA": 0,
      "peak_mA": 0,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "analog",
      "acdc": "dc"
    },
    "interfaces": [
      "analog"
    ]
  },
  {
    "id": "cat_aht20",
    "category": "sensor",
    "subtype": "Humidity",
    "name": "Aosong AHT20 temperature and humidity sensor",
    "manufacturer": "Aosong Guangzhou Elec",
    "lcsc": "C2757850",
    "mpn": "AHT20",
    "package": "SMD",
    "specs": {
      "Measures": "Humidity and temperature",
      "Humidity accuracy": "Two percent",
      "Interface": "I2C",
      "Cost": "Very low"
    },
    "pros": [
      "Cheap and very popular",
      "Both humidity and temperature",
      "Well stocked"
    ],
    "cons": [
      "Fixed single address, one per bus",
      "Needs a few milliseconds to settle"
    ],
    "use": "Low cost room comfort and weather logging.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588955056049958912",
    "lcscUrl": "https://www.lcsc.com/product-detail/Temperature-and-Humidity-Sensor_Aosong-Guangzhou-Elec-Aosong-Guangzhou-Elec-AHT20.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.2,
      "typ": 3.3,
      "max": 5.5
    },
    "current": {
      "active_mA": 0.25,
      "peak_mA": 0.5,
      "sleep_uA": 0.001
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_sht30_dis_b2_5ks",
    "category": "sensor",
    "subtype": "Humidity",
    "name": "Sensirion SHT30 temperature and humidity sensor",
    "manufacturer": "Sensirion",
    "lcsc": "C77361",
    "mpn": "SHT30-DIS-B2.5KS",
    "package": "DFN-8-EP 2.5x2.5",
    "specs": {
      "Measures": "Humidity and temperature",
      "Humidity accuracy": "Three percent",
      "Interface": "I2C",
      "Quality": "Reliable Swiss made part"
    },
    "pros": [
      "Trusted accuracy",
      "Two address options",
      "Good long term stability"
    ],
    "cons": [
      "Costs more than the AHT20",
      "Tiny package"
    ],
    "use": "Quality weather and comfort sensing that must stay accurate.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8586192474864308224",
    "lcscUrl": "https://www.lcsc.com/search?q=C77361",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.4,
      "typ": 3.3,
      "max": 5.5
    },
    "current": {
      "active_mA": 0.6,
      "peak_mA": 1.5,
      "sleep_uA": 0.002
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_sht31_dis_b2_5ks",
    "category": "sensor",
    "subtype": "Humidity",
    "name": "Sensirion SHT31 temperature and humidity sensor",
    "manufacturer": "Sensirion",
    "lcsc": "C80862",
    "mpn": "SHT31-DIS-B2.5kS",
    "package": "DFN-8-EP 2.5x2.5",
    "specs": {
      "Measures": "Humidity and temperature",
      "Humidity accuracy": "Two percent",
      "Interface": "I2C",
      "Extra": "Built in heater clears condensation"
    },
    "pros": [
      "Better accuracy than the SHT30",
      "Heater clears dew",
      "Solid stability"
    ],
    "cons": [
      "Higher cost",
      "Tiny package"
    ],
    "use": "Demanding humidity work, including damp places.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588881633809850368",
    "lcscUrl": "https://www.lcsc.com/search?q=C80862",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.4,
      "typ": 3.3,
      "max": 5.5
    },
    "current": {
      "active_mA": 0.6,
      "peak_mA": 1.5,
      "sleep_uA": 0.002
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_sht40_ad1b_r2",
    "category": "sensor",
    "subtype": "Humidity",
    "name": "Sensirion SHT40 temperature and humidity sensor",
    "manufacturer": "Sensirion",
    "lcsc": "C2909890",
    "mpn": "SHT40-AD1B-R2",
    "package": "DFN-4-EP 1.5x1.5",
    "specs": {
      "Measures": "Humidity and temperature",
      "Humidity accuracy": "1.8 percent",
      "Interface": "I2C",
      "Current": "Extremely low between readings"
    },
    "pros": [
      "Best accuracy and lowest power here",
      "Newest generation",
      "Tiny"
    ],
    "cons": [
      "Costs the most of the Sensirion parts",
      "Very small part"
    ],
    "use": "Battery humidity loggers that must run a long time.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588941046370226176",
    "lcscUrl": "https://www.lcsc.com/search?q=C2909890",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 1.08,
      "typ": 1.8,
      "max": 3.6
    },
    "current": {
      "active_mA": 0.32,
      "peak_mA": 0.5,
      "sleep_uA": 8e-05
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_htu21d",
    "category": "sensor",
    "subtype": "Humidity",
    "name": "TE HTU21D temperature and humidity sensor",
    "manufacturer": "TE Connectivity",
    "lcsc": "C83479",
    "mpn": "HTU21D",
    "package": "DFN-6-EP 3x3",
    "specs": {
      "Measures": "Humidity and temperature",
      "Humidity accuracy": "Two percent",
      "Interface": "I2C",
      "Maturity": "A long established part"
    },
    "pros": [
      "Good accuracy",
      "Low standby current",
      "Widely supported in code"
    ],
    "cons": [
      "One fixed address",
      "Surface mount only"
    ],
    "use": "A proven humidity and temperature sensor with lots of examples.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8586192520225705984",
    "lcscUrl": "https://www.lcsc.com/product-detail/Temperature-and-Humidity-Sensor_TE-Connectivity-TE-Connectivity-HTU21D.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 1.5,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 0.5,
      "peak_mA": 1.0,
      "sleep_uA": 0.0002
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_scw8916b",
    "category": "sensor",
    "subtype": "Water level",
    "name": "SinOne SCW8916B non-contact level sensor",
    "manufacturer": "SOC Shenzhen SinOne Microelectronics",
    "lcsc": "C93853",
    "mpn": "SCW8916B",
    "package": "SOP-16",
    "specs": {
      "Measures": "Liquid level through a container wall",
      "Method": "Senses through plastic, nothing touches the liquid",
      "Interface": "Serial, also called UART",
      "Outputs": "Four level steps"
    },
    "pros": [
      "Nothing touches the liquid so nothing corrodes",
      "Works through a tank wall",
      "Simple serial output"
    ],
    "cons": [
      "Coarse, a few level steps only",
      "Needs tuning to the wall thickness"
    ],
    "use": "Sensing water height in a sealed tank without a probe inside.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8586179807307059200",
    "lcscUrl": "https://www.lcsc.com/product-detail/Float-Level-Senors_SOCShenzhen-SinOne-Microelectronics-SOCShenzhen-SinOne-Microelectronics-SCW8916B.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 3.0,
      "typ": 5.0,
      "max": 5.5
    },
    "current": {
      "active_mA": 2.0,
      "peak_mA": 5.0,
      "sleep_uA": 1.0
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "uart"
    ]
  },
  {
    "id": "cat_mdc04",
    "category": "sensor",
    "subtype": "Water level",
    "name": "Mysentech MDC04 capacitive sensor",
    "manufacturer": "Mysentech",
    "lcsc": "C2843541",
    "mpn": "MDC04",
    "package": "QFN-20-EP 3x3",
    "specs": {
      "Measures": "Capacitance, used for liquid level or touch",
      "Resolution": "16 bit",
      "Interface": "I2C and single wire",
      "Range": "0 to 119 picofarads"
    },
    "pros": [
      "Flexible capacitive front end for a level pad",
      "Fine resolution",
      "Low current"
    ],
    "cons": [
      "You design the sensing pad yourself",
      "Needs calibration"
    ],
    "use": "Custom water level pads behind a non metal wall.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588919425978679296",
    "lcscUrl": "https://www.lcsc.com/product-detail/Float-Level-Senors_Mysentech-Mysentech-MDC04.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.0,
      "typ": 3.3,
      "max": 5.5
    },
    "current": {
      "active_mA": 0.5,
      "peak_mA": 1.0,
      "sleep_uA": 0.01
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_mdc02",
    "category": "sensor",
    "subtype": "Water level",
    "name": "Mysentech MDC02 capacitive sensor",
    "manufacturer": "Mysentech",
    "lcsc": "C3029620",
    "mpn": "MDC02",
    "package": "SOP-8",
    "specs": {
      "Measures": "Capacitance, used for liquid level or touch",
      "Interface": "Single wire",
      "Use": "Simple level or proximity pads"
    },
    "pros": [
      "Very small and cheap",
      "Single wire keeps wiring simple",
      "Good for a basic level pad"
    ],
    "cons": [
      "Fewer features than the MDC04",
      "You build the sensing pad"
    ],
    "use": "Low cost single point water present or absent sensing.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8603031055456743424",
    "lcscUrl": "https://www.lcsc.com/search?q=C3029620",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.0,
      "typ": 3.3,
      "max": 5.5
    },
    "current": {
      "active_mA": 0.5,
      "peak_mA": 1.0,
      "sleep_uA": 0.01
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "onewire"
    ]
  },
  {
    "id": "cat_mc11t",
    "category": "sensor",
    "subtype": "Water level",
    "name": "Mysentech MC11T capacitive sensor",
    "manufacturer": "Mysentech",
    "lcsc": "C19188777",
    "mpn": "MC11T",
    "package": "TSSOP-16",
    "specs": {
      "Measures": "Capacitance for liquid level",
      "Resolution": "16 bit",
      "Interface": "I2C",
      "Range": "1 to 1000 picofarads"
    },
    "pros": [
      "Wide capacitance range",
      "Fine resolution",
      "Two channels"
    ],
    "cons": [
      "Needs a designed sensing pad",
      "Calibration required"
    ],
    "use": "Multi point water level sensing with capacitive pads.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8590908701190668288",
    "lcscUrl": "https://www.lcsc.com/product-detail/Float-Level-Senors_Mysentech-Mysentech-MC11T.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.0,
      "typ": 3.3,
      "max": 5.5
    },
    "current": {
      "active_mA": 0.5,
      "peak_mA": 1.0,
      "sleep_uA": 0.01
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_mcp62",
    "category": "sensor",
    "subtype": "Water level",
    "name": "Mysentech MCP62 capacitive sensor",
    "manufacturer": "Mysentech",
    "lcsc": "C22390079",
    "mpn": "MCP62",
    "package": "QSOP-24",
    "specs": {
      "Measures": "Capacitance for level or touch",
      "Resolution": "16 bit",
      "Interface": "I2C, serial, and SPI",
      "Channels": "Two"
    },
    "pros": [
      "Several interface choices",
      "Fine resolution",
      "Flexible"
    ],
    "cons": [
      "Larger and pricier",
      "You design the pad"
    ],
    "use": "Capacitive level sensing where you want a choice of bus.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8590909368651235328",
    "lcscUrl": "https://www.lcsc.com/product-detail/Float-Level-Senors_Mysentech-Mysentech-MCP62.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.5,
      "typ": 3.3,
      "max": 5.5
    },
    "current": {
      "active_mA": 0.5,
      "peak_mA": 1.0,
      "sleep_uA": 0.01
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi",
      "uart"
    ]
  },
  {
    "id": "cat_adxl345bccz_rl7",
    "category": "sensor",
    "subtype": "Acceleration",
    "name": "Analog Devices ADXL345 accelerometer",
    "manufacturer": "Analog Devices",
    "lcsc": "C9667",
    "mpn": "ADXL345BCCZ-RL7",
    "package": "LGA-14 3x5",
    "specs": {
      "Measures": "Acceleration on three axes",
      "Range": "Plus or minus 2 to 16 g",
      "Interface": "I2C and SPI",
      "Extra": "Tap and free fall detection"
    },
    "pros": [
      "Classic, very well supported",
      "Tap and free fall built in",
      "Low current"
    ],
    "cons": [
      "Older part, modest noise",
      "Tiny package"
    ],
    "use": "Tilt, tap, motion wake, and step counting.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8578540464525328384",
    "lcscUrl": "https://www.lcsc.com/product-detail/Attitude-Sensor-Gyroscope_Analog-Devices-Analog-Devices-ADXL345BCCZ-RL7.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.0,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 0.14,
      "peak_mA": 0.2,
      "sleep_uA": 0.0001
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi"
    ]
  },
  {
    "id": "cat_lis3dhtr",
    "category": "sensor",
    "subtype": "Acceleration",
    "name": "ST LIS3DH accelerometer",
    "manufacturer": "STMicroelectronics",
    "lcsc": "C15134",
    "mpn": "LIS3DHTR",
    "package": "LGA-16 3x3",
    "specs": {
      "Measures": "Acceleration on three axes",
      "Range": "Plus or minus 2 to 16 g",
      "Interface": "I2C and SPI",
      "Current": "Very low"
    },
    "pros": [
      "Very low power",
      "Tiny",
      "Cheap and common"
    ],
    "cons": [
      "More noise than premium parts",
      "Small part to solder"
    ],
    "use": "Low power motion and tilt sensing in wearables.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8586177415076843520",
    "lcscUrl": "https://www.lcsc.com/product-detail/Attitude-Sensor-Gyroscope_STMicroelectronics-STMicroelectronics-LIS3DHTR.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 1.71,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 0.01,
      "peak_mA": 0.1,
      "sleep_uA": 0.0005
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi"
    ]
  },
  {
    "id": "cat_mma8452qr1",
    "category": "sensor",
    "subtype": "Acceleration",
    "name": "NXP MMA8452Q accelerometer",
    "manufacturer": "NXP Semicon",
    "lcsc": "C11360",
    "mpn": "MMA8452QR1",
    "package": "QFN-16 3x3",
    "specs": {
      "Measures": "Acceleration on three axes",
      "Range": "Plus or minus 2 to 8 g",
      "Interface": "I2C",
      "Resolution": "12 bit"
    },
    "pros": [
      "Good resolution for the price",
      "Simple to use",
      "Well documented"
    ],
    "cons": [
      "I2C only",
      "Older design"
    ],
    "use": "Orientation and motion where I2C is fine.",
    "datasheet": "https://www.nxp.com.cn/docs/en/data-sheet/MMA8452Q.pdf",
    "lcscUrl": "https://www.lcsc.com/product-detail/Attitude-Sensor-Gyroscope_NXP-Semicon-NXP-Semicon-MMA8452QR1.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 1.95,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 0.17,
      "peak_mA": 0.25,
      "sleep_uA": 0.001
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_lsm6ds3tr_c",
    "category": "sensor",
    "subtype": "Acceleration",
    "name": "ST LSM6DS3 motion sensor",
    "manufacturer": "STMicroelectronics",
    "lcsc": "C967633",
    "mpn": "LSM6DS3TR-C",
    "package": "LGA-14 2.5x3",
    "specs": {
      "Measures": "Acceleration and rotation, six axes",
      "Interface": "I2C and SPI",
      "Extra": "Step counter and gesture engine",
      "Buffer": "Built in first in first out store"
    },
    "pros": [
      "Accelerometer and gyroscope in one",
      "On chip step counting",
      "Good value"
    ],
    "cons": [
      "More setup than a plain accelerometer",
      "Uses more current with the gyroscope on"
    ],
    "use": "Motion tracking that needs both tilt and turn.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588905119282421760",
    "lcscUrl": "https://www.lcsc.com/product-detail/Attitude-Sensor-Gyroscope_STMicroelectronics-STMicroelectronics-LSM6DS3TR-C.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 1.71,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 0.9,
      "peak_mA": 1.5,
      "sleep_uA": 0.003
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi"
    ]
  },
  {
    "id": "cat_qmi8658a",
    "category": "sensor",
    "subtype": "Acceleration",
    "name": "QST QMI8658A motion sensor",
    "manufacturer": "QST",
    "lcsc": "C3021082",
    "mpn": "QMI8658A",
    "package": "LGA-14",
    "specs": {
      "Measures": "Acceleration and rotation, six axes",
      "Interface": "I2C and SPI",
      "Stock": "Very well stocked and cheap"
    },
    "pros": [
      "Low cost six axis part",
      "Plentiful supply",
      "Good for hobby motion projects"
    ],
    "cons": [
      "Smaller code ecosystem than ST parts",
      "Datasheet is less polished"
    ],
    "use": "Budget motion sensing for drones, wearables, and robots.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8589834393876934656",
    "lcscUrl": "https://www.lcsc.com/product-detail/Attitude-Sensor-Gyroscope_QST-QST-QMI8658A.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 1.71,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 1.5,
      "peak_mA": 3.0,
      "sleep_uA": 0.005
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi"
    ]
  },
  {
    "id": "cat_icm_20948",
    "category": "sensor",
    "subtype": "Rotation",
    "name": "TDK ICM-20948 nine axis motion sensor",
    "manufacturer": "TDK InvenSense",
    "lcsc": "C726001",
    "mpn": "ICM-20948",
    "package": "QFN-24 3x3",
    "specs": {
      "Measures": "Acceleration, rotation, and magnetic heading, nine axes",
      "Interface": "I2C and SPI",
      "Use": "Full orientation in space"
    },
    "pros": [
      "Full nine axis orientation",
      "Compass included",
      "Trusted brand"
    ],
    "cons": [
      "Higher current",
      "Fusion maths is involved"
    ],
    "use": "Heading and orientation for drones, robots, and head tracking.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588885225937625088",
    "lcscUrl": "https://www.lcsc.com/product-detail/Accelerometers_TDK-InvenSense-TDK-InvenSense-ICM-20948.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 1.71,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 3.0,
      "peak_mA": 5.0,
      "sleep_uA": 0.008
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi"
    ]
  },
  {
    "id": "cat_mt6825gt_std",
    "category": "sensor",
    "subtype": "Rotation",
    "name": "MagnTek MT6825 magnetic angle encoder",
    "manufacturer": "Magn Tek",
    "lcsc": "C5144620",
    "mpn": "MT6825GT-STD",
    "package": "TSSOP-16",
    "specs": {
      "Measures": "Absolute shaft angle, zero to 360 degrees",
      "Method": "Reads a small magnet on the shaft end",
      "Interface": "SPI, plus stepped and pulse outputs",
      "Resolution": "High, suited to motor control"
    },
    "pros": [
      "True absolute angle, no homing needed",
      "Contactless so nothing wears out",
      "Good for motor position control"
    ],
    "cons": [
      "Needs a magnet aligned on the shaft",
      "Careful placement matters"
    ],
    "use": "Knowing the exact angle of a motor or a knob shaft.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8589789174439047168",
    "lcscUrl": "https://www.lcsc.com/search?q=C5144620",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 3.0,
      "typ": 5.0,
      "max": 5.5
    },
    "current": {
      "active_mA": 8.0,
      "peak_mA": 12.0,
      "sleep_uA": 0.01
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "spi"
    ]
  },
  {
    "id": "cat_mlx90363kdc_abb_000_re",
    "category": "sensor",
    "subtype": "Rotation",
    "name": "Melexis MLX90363 magnetic angle sensor",
    "manufacturer": "Melexis",
    "lcsc": "C2654946",
    "mpn": "MLX90363KDC-ABB-000-RE",
    "package": "SOIC-8",
    "specs": {
      "Measures": "Shaft angle from a magnet",
      "Interface": "SPI",
      "Quality": "Automotive grade"
    },
    "pros": [
      "Rugged automotive part",
      "Contactless angle",
      "SPI output"
    ],
    "cons": [
      "Costs more",
      "Needs a magnet on the shaft"
    ],
    "use": "Reliable angle sensing in tough conditions.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588931191223832576",
    "lcscUrl": "https://www.lcsc.com/product-detail/Hall-Sensor_Melexis-Melexis-MLX90363KDC-ABB-000-RE.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 3.0,
      "typ": 5.0,
      "max": 5.5
    },
    "current": {
      "active_mA": 10.0,
      "peak_mA": 15.0,
      "sleep_uA": 0.01
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "spi"
    ]
  },
  {
    "id": "cat_a1324llhlt_t",
    "category": "sensor",
    "subtype": "Rotation",
    "name": "Allegro A1324 linear hall sensor",
    "manufacturer": "Allegro MicroSystems LLC",
    "lcsc": "C163316",
    "mpn": "A1324LLHLT-T",
    "package": "SOT-23W",
    "specs": {
      "Measures": "Magnetic field strength, analog",
      "Output": "A voltage that tracks the field",
      "Interface": "Analog",
      "Use": "Position and rotation with a magnet"
    },
    "pros": [
      "Simple analog output",
      "Cheap",
      "Good for sensing a passing magnet"
    ],
    "cons": [
      "Needs an analog input",
      "Five volt supply"
    ],
    "use": "Counting turns or sensing a magnet glide past.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588881315931803648",
    "lcscUrl": "https://www.lcsc.com/product-detail/Hall-Sensor_Allegro-MicroSystems%2C-LLC-Allegro-MicroSystems%2C-LLC-A1324LLHLT-T.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 4.5,
      "typ": 5.0,
      "max": 5.5
    },
    "current": {
      "active_mA": 8.0,
      "peak_mA": 12.0,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "analog"
    ]
  },
  {
    "id": "cat_a1220lua_t",
    "category": "sensor",
    "subtype": "Rotation",
    "name": "Allegro A1220 hall switch",
    "manufacturer": "Allegro MicroSystems LLC",
    "lcsc": "C113729",
    "mpn": "A1220LUA-T",
    "package": "TO-92S",
    "specs": {
      "Measures": "Magnet present or not",
      "Output": "A simple on or off pin",
      "Interface": "Digital",
      "Supply": "Wide, 3.8 to 24 volts"
    },
    "pros": [
      "Direct digital output, no analog needed",
      "Wide supply range",
      "Very cheap"
    ],
    "cons": [
      "On or off only, no field strength",
      "Needs a pull-up on the output"
    ],
    "use": "Counting wheel turns and end stop detection with a magnet.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588889767626465280",
    "lcscUrl": "https://www.lcsc.com/product-detail/Hall-Sensor_Allegro-MicroSystems%2C-LLC-Allegro-MicroSystems%2C-LLC-A1220LUA-T.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 3.8,
      "typ": 5.0,
      "max": 24.0
    },
    "current": {
      "active_mA": 5.0,
      "peak_mA": 10.0,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "digital"
    ]
  },
  {
    "id": "cat_bmp388",
    "category": "sensor",
    "subtype": "Pressure",
    "name": "Bosch BMP388 pressure sensor",
    "manufacturer": "Bosch Sensortec",
    "lcsc": "C779278",
    "mpn": "BMP388",
    "package": "LGA-10 2x2",
    "specs": {
      "Measures": "Air pressure and temperature",
      "Use": "Altitude to about 0.5 metres",
      "Interface": "I2C and SPI",
      "Quality": "Low noise"
    },
    "pros": [
      "Fine altitude resolution",
      "Low noise",
      "Small"
    ],
    "cons": [
      "Needs an open vent to the air",
      "Tiny part"
    ],
    "use": "Altitude for drones and weather stations.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588918725961789440",
    "lcscUrl": "https://www.lcsc.com/product-detail/Pressure-Sensors_Bosch-Sensortec-Bosch-Sensortec-BMP388.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 1.7,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 0.5,
      "peak_mA": 1.0,
      "sleep_uA": 0.002
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi"
    ]
  },
  {
    "id": "cat_bmp280",
    "category": "sensor",
    "subtype": "Pressure",
    "name": "Bosch BMP280 pressure sensor",
    "manufacturer": "Bosch Sensortec",
    "lcsc": "C83291",
    "mpn": "BMP280",
    "package": "LGA-8 2x2.5",
    "specs": {
      "Measures": "Air pressure and temperature",
      "Interface": "I2C and SPI",
      "Cost": "Low"
    },
    "pros": [
      "Cheap and popular",
      "Low power",
      "Lots of code support"
    ],
    "cons": [
      "Less precise than the BMP388",
      "Needs a vent"
    ],
    "use": "Basic altitude and weather sensing.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588881905890156544",
    "lcscUrl": "https://www.lcsc.com/product-detail/Pressure-Sensors_Bosch-Sensortec-Bosch-Sensortec-BMP280.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 1.7,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 0.5,
      "peak_mA": 1.0,
      "sleep_uA": 0.0001
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi"
    ]
  },
  {
    "id": "cat_lps22hbtr",
    "category": "sensor",
    "subtype": "Pressure",
    "name": "ST LPS22HB pressure sensor",
    "manufacturer": "STMicroelectronics",
    "lcsc": "C94049",
    "mpn": "LPS22HBTR",
    "package": "HLGA-10_2x2mm",
    "specs": {
      "Measures": "Air pressure and temperature",
      "Current": "Very low",
      "Interface": "I2C and SPI"
    },
    "pros": [
      "Very low power",
      "Small",
      "Good for wearables"
    ],
    "cons": [
      "Modest resolution",
      "Tiny part"
    ],
    "use": "Low power altitude sensing in small devices.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8579642802705530880",
    "lcscUrl": "https://www.lcsc.com/product-detail/Pressure-Sensors_STMicroelectronics-STMicroelectronics-LPS22HBTR.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 1.7,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 0.01,
      "peak_mA": 0.05,
      "sleep_uA": 0.001
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi"
    ]
  },
  {
    "id": "cat_bme280",
    "category": "sensor",
    "subtype": "Pressure",
    "name": "Bosch BME280 environment sensor",
    "manufacturer": "Bosch Sensortec",
    "lcsc": "C92489",
    "mpn": "BME280",
    "package": "LGA-8 2.5x2.5",
    "specs": {
      "Measures": "Temperature, humidity, and pressure, all in one",
      "Interface": "I2C and SPI",
      "Use": "A complete weather sensor"
    },
    "pros": [
      "Three measurements in one chip",
      "Very popular, easy to find code",
      "Low power"
    ],
    "cons": [
      "Costs more than single function parts",
      "Needs a vent to the air"
    ],
    "use": "A one chip weather station: warmth, damp, and altitude.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8588886911167029248",
    "lcscUrl": "https://www.lcsc.com/product-detail/Temperature-and-Humidity-Sensor_Bosch-Sensortec-Bosch-Sensortec-BME280.html",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 1.7,
      "typ": 3.3,
      "max": 3.6
    },
    "current": {
      "active_mA": 0.5,
      "peak_mA": 1.0,
      "sleep_uA": 0.0001
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c",
      "spi"
    ]
  },
  {
    "id": "cat_scd40_d_r2",
    "category": "sensor",
    "subtype": "Air quality",
    "name": "Sensirion SCD40 carbon dioxide sensor",
    "manufacturer": "See datasheet",
    "lcsc": "C3659421",
    "mpn": "SCD40-D-R2",
    "package": "LGA-20 10.1x10.1",
    "specs": {
      "Measures": "Carbon dioxide, plus temperature and humidity",
      "Method": "True optical carbon dioxide measurement",
      "Interface": "I2C",
      "Note": "Draws a large current spike during a reading"
    },
    "pros": [
      "Real carbon dioxide reading, not a guess",
      "Compact for its type",
      "Includes warmth and damp"
    ],
    "cons": [
      "Large current spikes need a buffer capacitor",
      "Higher cost"
    ],
    "use": "Indoor air quality and ventilation control.",
    "datasheet": "https://jlcpcb.com/api/file/downloadByFileSystemAccessId/8589834442203299840",
    "lcscUrl": "https://www.lcsc.com/search?q=C3659421",
    "preferred": false,
    "verified": true,
    "role": "sensor",
    "voltage": {
      "min": 2.4,
      "typ": 3.3,
      "max": 5.5
    },
    "current": {
      "active_mA": 15.0,
      "peak_mA": 205.0,
      "sleep_uA": 0.5
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "i2c"
    ]
  },
  {
    "id": "cat_turbidity_sensor_module",
    "category": "sensor",
    "subtype": "Turbidity",
    "name": "Turbidity sensor module",
    "manufacturer": "Various module makers",
    "lcsc": null,
    "mpn": null,
    "package": null,
    "specs": {
      "Measures": "How cloudy water is",
      "Method": "Shines light across the water and reads how much passes",
      "Interface": "Analog voltage",
      "Note": "Sold as a finished probe, not a chip"
    },
    "pros": [
      "Simple analog reading",
      "Direct measure of water clarity"
    ],
    "cons": [
      "Not a single LCSC stock part",
      "Needs calibration to real samples"
    ],
    "use": "Water quality projects that watch how cloudy the water is.",
    "datasheet": null,
    "lcscUrl": null,
    "preferred": false,
    "verified": false,
    "role": "sensor",
    "voltage": {
      "min": 3.3,
      "typ": 5.0,
      "max": 5.5
    },
    "current": {
      "active_mA": 8,
      "peak_mA": 40,
      "sleep_uA": 0
    },
    "signal": {
      "domain": "mixed",
      "acdc": "dc"
    },
    "interfaces": [
      "analog"
    ],
    "note": "No turbidity sensor is confirmed in the parts dataset, so this entry is unverified. Source a turbidity probe module separately and read its analog output."
  }
];
